services:
  -  type: web
     name: healr-api
     runtime: python
     plan: free
     autodeploy: false
     buildCommand: pip install -r requirements.txt
     startCommand: python -m uvicorn api:app --host 0.0.0.0 --port 8000